# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0006_auto_20160524_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, verbose_name='Ticket Number')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='river.State')),
            ],
            managers=[
                ('workflow', django.db.models.manager.Manager()),
            ],
        ),
    ]
